spring.application.name=ECommerce-Online_Book_Store

#===========cfgs database====================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Eccomerce-Online-BookStore
spring.datasource.username=root
spring.datasource.password=root


#==========JPA Properties=======
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#=============server=========
